name: Run isort
on:
  - push

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: isort/isort-action@master
        with:
          configuration: --profile black -l 120
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Applied automatic fixes from linters'
